name: Linter

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  lint:
    name: Run Super-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7.3.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JAVASCRIPT: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSX: false
          VALIDATE_JSON: false
          VALIDATE_JSONC: false
          VALIDATE_PHP: false
