name: Super Linter

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Run Super Linter
    - name: Run Super Linter
      uses: super-linter/super-linter@v7.3.0
      env:
        RUN_LOCAL: true
